site:
  title: Building the AI Engine
  start_page: rhoai34-practical::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  extensions:
  - '@asciidoctor/tabs'
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
